---
- name: Stop etcd and clean data dir on all nodes in parallel
  hosts: etcd_nodes
  become: true
  strategy: free

  tasks:
    - name: Stop etcd service
      systemd:
        name: etcd
        state: stopped
        enabled: no

    - name: Remove /var/lib/etcd directory
      file:
        path: /var/lib/etcd
        state: absent

